pcd_file: "/home/hyss/localization/snu_local/src/snu_localization/map/303_map.pcd"


I_L_extrinsic: [1.0, 0.0, 0.0, -0.011,
                0.0, 1.0, 0.0, -0.02329,
                0.0, 0.0, 1.0, 0.04412,
                0.0, 0.0, 0.0, 1.0]   



pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
